# Set base image (host OS)
FROM python:3

# By default, listen on port 5000
EXPOSE 5000/tcp

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    python -m spacy download en_core_web_md

# Copy the content of the local src directory to the working directory
COPY app.py pun.py 
COPYscrape-data/ ./scrape-data/

# Specify the command to run on container start
CMD [ "python", "./app.py" ]